import { GetStaticProps } from 'next'
import Head from 'next/head'


interface IPropsHome {

}


export default function Home({ }: IPropsHome) {
  return (
    <div >
      <Head>
        <title>Spider-Man - Create designer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main >

      </main>

      <footer>

      </footer>
    </div>
  )
}


export const getStaticProps: GetStaticProps = () => {



  return {
    props: {

    },
    revalidate:60 *1 //
  }

}
